### ISSUE TITLE
Chroniker sends email every minute. I need to stop it.

### ISSUE THREAD

**Issue by russian-master** [chrisspen/django-chroniker#101]
I set this command in cron:

* * * * * /home/env/project/bin/python /home/env/project/project/manage.py cron

Now it sends me email every minute! 

_0 total stale jobs.
0 Jobs are due.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
All jobs complete!_

How can I stop it?

**Comment by rosenhagen** [comment]
Running the cronjob produces text output (messages etc.). I don't know what system you are running, but chances are that if there is output during the cronjob, that it by default is send as an email to the user that the cronjob is running for (you), so that errors etc. won't go unnoticed.

You might want to redirect the output to a log file. 
`* * * * * ... /home/env/project/bin/python /home/env/project/project/manage.py cron  2>&1 >>chroniker.log`

(Take care, the log will grow over time and should be "rotated")

If you don't care about the output at all, you could redirect it straight to the trash.
`* * * * * ... /home/env/project/bin/python /home/env/project/project/manage.py cron  2>&1 >>/dev/null`

Your mileage may vary.

**Comment by russian-master** [comment]
If I set `>>/dev/null` then I won't be notified if something nasty happens?
Besides I guess it's not good practice to print in cron jobs.

It worked though. Thank you.
